version: "0.5"
is_strict: true
environment:
  - NGINX_WEB_PORT=8000
  - STATIC=$DEVBOX_PROJECT_ROOT/static/
  - MEDIA=$DEVBOX_PROJECT_ROOT/media/

processes:
  db:
    command: "docker-compose -f docker-compose-db.yml up"
    availability:
      restart: on_failure
      max_restarts: 5
  app_server:
    command: |
      python manage.py collectstatic --noinput
      python manage.py wait_for_db
      python manage.py check --database default
      python manage.py migrate
      ./scripts/run.sh
    depends_on:
      db:
        condition: process_started
