version: "0.5"

processes:
  nginx:
    environment:
      - STATIC=$DEVBOX_PROJECT_ROOT/data/web/static/
      - MEDIA=$DEVBOX_PROJECT_ROOT/data/web/media/
    command: |
      if [ -f $NGINX_CONFDIR/nginx.template ]; then envsubst $(awk 'BEGIN {for (k in ENVIRON) {printf "$"k","}}') < $NGINX_CONFDIR/nginx.template > $NGINX_CONFDIR/nginx.conf; fi
      nginx -p $NGINX_PATH_PREFIX -c $NGINX_CONFDIR/nginx.conf -e error.log -g "pid nginx.pid;daemon off;"
    availability:
      restart: on_failure
      max_restarts: 5
  nginx-error:
    command: "tail -f $NGINX_PATH_PREFIX/error.log"
    availability:
      restart: "always"
  nginx-access:
    command: "tail -f $NGINX_PATH_PREFIX/access.log"
    availability:
      restart: "always"
  db:
    command: "docker-compose -f docker-compose-db.yml up --detach"
    availability:
      restart: on_failure
      max_restarts: 5
  runserver:
    command: |
      python manage.py collectstatic --noinput
      python manage.py wait_for_db
      python manage.py check --database default
      python manage.py migrate
      ./scripts/run.sh
    depends_on:
      db:
        condition: process_started
